### ISSUE TITLE
No matching licenses left on the server

### ISSUE THREAD

**Issue by Ren-yibo** [yhjaicly/idea2022-unlockTool#1]
![image](https://user-images.githubusercontent.com/22462370/169256113-ae4caa0c-0797-4bcd-a249-d2b746c72ef9.png)
问下有没有遇到这个错误

**Comment by Tycoon-HJ** [comment]
这个是激活idea的，插件不支持，我开启代理之后也无法激活，试着把代理关一下，然后重新打开idea
